### ISSUE TITLE
Balanced code  unordered codes python Donald Knuth

### ISSUE THREAD

**Issue by Sandy4321** [supermihi/lpdec#2]
do you have encoder for 
https://en.wikipedia.org/wiki/Constant-weight_code
Balanced code[edit]
In coding theory, a balanced code is a binary forward error correction code for which each codeword contains an equal number of zero and one bits. Balanced codes have been introduced by Donald Knuth;[5] they are a subset of so-called unordered codes, which are codes having the property that the positions of ones in a codeword are never a subset of the positions of the ones in another codeword. Like all unordered codes, balanced codes are suitable for the detection of all unidirectional errors in an encoded message. Balanced codes allow for particularly efficient decoding, which can be carried out in parallel.[5][6][7]
Some of the more notable uses of balanced-weight codes include biphase mark code uses a 1 of 2 code; 6b/8b encodinguses a 4 of 8 code; the Hadamard code is a   of   code (except for the zero codeword), the three-of-six code; etc
Balanced code  unordered codes python Donald Knuth

**Comment by supermihi** [comment]
Hi Sandy,
no, unfortunatelly this package does not contain such an encoder.
